version: '3.3'
services:
    mmdev:
        ports:
            - '8000:8000'
        container_name: mftmdev
        image: 'mftmdev:latest'
        volumes:
            - ./src/webapp:/code
        working_dir: /code
        command: python3 manage.py runserver 0.0.0.0:8000